### ISSUE TITLE
Jobs metrices are not exposed only pipelines

### ISSUE THREAD

**Issue by ielshal** [radiofrance/gitlab-ci-pipelines-exporter#193]
**Describe**
Not sure if this is a bug os something missing in configurations but i can fetch pipeline matrices however job metrics i can not, in original pipeline exporter mvisonneau/gitlab-ci-pipelines-exporter you need to allow this as it is not on by default as per this [line](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/docs/configuration_syntax.md?plain=1#L300) by adding below in pull section

```
        pipeline:
          jobs:
            enabled: true
            from_child_pipelines:
              enabled: true
            runner_description:
              enabled: true
              aggregation_regexp: ".*"
```

how this can be achieved .. what i understood from docs here it should be exposed without need to do anything.
